[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; object-src 'none'; font-src 'self' fonts.gstatic.com; style-src 'self' fonts.googleapis.com 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self' data:; frame-ancestors 'none'; upgrade-insecure-requests; block-all-mixed-content;"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "https://delphi-strategy.com/some-notes/*"
  to = "https://publish.obsidian.md/serve?url=www.delphi-strategy.com/some-notes/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.delphi-strategy.com/some-notes/*"
  to = "https://publish.obsidian.md/serve?url=www.delphi-strategy.com/some-notes/:splat"
  status = 200
  force = true
